[package]
name = "korangar_packets"
version = "0.1.0"
edition = "2024"

[lib]
name = "korangar_packets"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.38.0", features = ["nif_version_2_17"] }
ragnarok-packets = { git = "https://github.com/vE5li/korangar", rev = "f06ad6d16519f0d2c28711a30f7d68f12c1b3cfb", features = ["derive"] }
ragnarok-bytes = { git = "https://github.com/vE5li/korangar", rev = "f06ad6d16519f0d2c28711a30f7d68f12c1b3cfb", features = ["derive"] }
